pub mod action;
pub mod args;
pub mod command;
pub mod component;
pub mod config;
pub mod file;
pub mod input;
pub mod log;
pub mod modal;
pub mod notification;
pub mod render;
pub mod run;
pub mod status_line;
pub mod theme;
pub mod window;
pub mod highlight;

pub use args::parse_args;
pub use run::run;
